### PR TITLE
Added verbose logging

### PR DESCRIPTION
**Pull request by patriotyk**
@cajun-rat @tjamison 
For aktualizr this functionality helped us to find the problem with big messages.

### CODE REVIEW

**Comment by gunnarx** [comment]
Have you considered adding DLT logging instead? 
It's very useful to have all logs to the same place, to get logs efficiently transferred offboard and channelled all logs through a system that can output in different ways.

**Comment by cajun-rat** [comment]
@gunnarx I guess that would be a possibility, but I don't know whether a component like rvi_lib (which is will generally be a 'leaf node' in the library dependency tree) should take a hard dependency on a specific logging framework.  For our use of rvi_lib, a simple on/off flag for low level debugging is enough.  That said, I can see that DLT logging would be nice (as a compile-time switch) for projects that are DLT-enabled already.

**Comment by gunnarx** [comment]
@cajun-rat wrote:
>  I guess that would be a possibility, but I don't know whether a component like rvi_lib (which is will generally be a 'leaf node' in the library dependency tree) should take a hard dependency on a specific logging framework. 

1. You're right, but *you* added "hard".
2. As far as GENIVI-created dependencies DLT is one of the more well accepted ones.  This PR is also making some assumptions about stderr being a viable output stream during the library's use.
3. Following the logic maybe RVI as a leaf library shouldn't be printing stuff either.

> For our use of rvi_lib, a simple on/off flag for low level debugging is enough. 

On/off flag is a separate issue

> That said, I can see that DLT logging would be nice (as a compile-time switch) for projects that are DLT-enabled already.

Exactly, so why wouldn't you start by assuming that is what I meant?

(For the record, "DLT-enabled" is every GENIVI-compliant project.)

**Comment by cajun-rat** [comment]
Hi @gunnarx 

>> I guess that would be a possibility, but I don't know whether a component like rvi_lib (which is will generally be a 'leaf node' in the library dependency tree) should take a hard dependency on a specific logging framework.
>
> You're right, but you added "hard".
>
>> That said, I can see that DLT logging would be nice (as a compile-time switch) for projects that are DLT-enabled already.
>
> Exactly, so why wouldn't you start by assuming that is what I meant?

I'm not trying to be difficult here--my understanding of your response was that you were suggesting using DLT instead of this if(verbose) fprintf(..) patch.  I'm sure the rvi_lib maintainers would be happy to review PR's implementing that, but my point was that as a consumer of the library I would prefer it if I could use rvi_lib without needing to also adopt DLT.

> Following the logic maybe RVI as a leaf library shouldn't be printing stuff either.

This is a valid concern, but my view was that the extra complexity to required to define some kind of API to make the logging output pluggable outweighs the benefit, at least at this time. This 'verbose' option is only intended to be used for low-level debugging, and I see it as a small step away from inserting temporary debugging printf-s.

> This PR is also making some assumptions about stderr being a viable output stream during the library's use.

That is true: applications that don't want output on stderr (for whatever reason) will need to avoid setting the option.

**Comment by cajun-rat** [comment]
Of course, if GENIVI wants to reject this patch, that is fine.  I just want to make sure you understand the reasoning behind the design.

**Comment by gunnarx** [comment]
> Of course, if GENIVI wants to reject this patch, that is fine. I just want to make sure you understand the reasoning behind the design.

Your last explanation was fine and I think we have exhausted the subject.  The project maintainer ultimately decides.

**Comment by tjamison** [comment]
This PR had some conflicts with the master branch after merging PRs #37 and #36. I've resolved the conflicts: @patriotyk or @cajun-rat, would you review to confirm?

Gunnar raises a good point about DLT which is worth considering as a feature request. For now, this has value in development, so I'm inclined to merge.

**Review by patriotyk — COMMENTED** [review]
Looks good to me

**Comment by cajun-rat** [comment]
Thank you!

**Pull request merged**
